server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://authentication-service:8081
          predicates: [Path=/api/v1/auth/**]
          filters: [JwtAuthenticationFilter]
        - id: customer-service
          uri: http://customer-service:8082
          predicates: [Path=/api/v1/customers/**]
          filters: [JwtAuthenticationFilter]
        - id: account-service
          uri: http://account-service:8083
          predicates: [Path=/api/v1/accounts/**]
          filters: [JwtAuthenticationFilter]
        - id: transaction-service
          uri: http://transaction-service:8084
          predicates: [Path=/api/v1/transactions/**]
          filters: [JwtAuthenticationFilter]
        - id: payment-service
          uri: http://payment-service:8085
          predicates: [Path=/api/v1/payments/**]
          filters: [JwtAuthenticationFilter]
        - id: notification-service
          uri: http://notification-service:8086
          predicates: [Path=/api/v1/notifications/**]
          filters: [JwtAuthenticationFilter]
        - id: fraud-detection-service
          uri: http://fraud-detection-service:8087
          predicates: [Path=/api/v1/fraud/**]
          filters: [JwtAuthenticationFilter]
